name: Deploy Terraform modules

on:
  push:
    branches:
      - main
    paths:
      - "azure-enterprise-terraform/**"
  workflow_dispatch:
    inputs:
      stack_path:
        description: "Terraform working dir (e.g. terraform/stacks/dev/platform)"
        required: true
        default: "terraform/stacks/dev/platform"
      force_unlock:
        description: "Force unlock state (ONLY if you know it's stale)"
        type: boolean
        required: false
        default: false
      lock_id:
        description: "Lock ID from the error output (GUID)"
        required: false
        default: ""

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Prevent concurrent runs from fighting over the same state
    concurrency:
      group: tf-${{ github.ref }}-${{ inputs.stack_path }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login --service-principal \
            -u "${{ secrets.ARM_CLIENT_ID }}" \
            -p "${{ secrets.ARM_CLIENT_SECRET }}" \
            --tenant "${{ secrets.ARM_TENANT_ID }}"
          az account set --subscription "${{ secrets.ARM_SUBSCRIPTION_ID }}"

      - name: Terraform Init
        working-directory: ${{ inputs.stack_path }}
        run: terraform init -upgrade

      - name: Force unlock (manual use)
        if: ${{ inputs.force_unlock == true && inputs.lock_id != '' }}
        working-directory: ${{ inputs.stack_path }}
        run: terraform force-unlock -force "${{ inputs.lock_id }}"

      - name: Terraform Plan
        working-directory: ${{ inputs.stack_path }}
        run: terraform plan -lock-timeout=5m
      - name: Terraform Destroy
        working-directory: ${{ inputs.stack_path }}
        run: terraform destroy -lock-timeout=5m -auto-approve

      - name: Remove Key Vault objects from state (unblock refresh)
        shell: bash
        working-directory: ${{ inputs.stack_path }}
        run: |
            set -euo pipefail
            terraform init -reconfigure

            echo "State objects containing keyvault:"
            terraform state list | grep -i keyvault || true

            # Remove ALL keyvault-related objects from state (safe: does NOT delete Azure resources)
            for addr in $(terraform state list | grep -i keyvault || true); do
            echo "Removing from state: $addr"
            terraform state rm "$addr" || true
            done

      - name: Reset terraform local dir (safe)
        shell: bash
        working-directory: ./azure-enterprise-terraform/terraform/stacks/dev/platform
        run: |
            rm -rf .terraform .terraform.lock.hcl
            terraform init -reconfigure

      - name: Terraform Init Modules
        working-directory: ./azure-enterprise-terraform/terraform/stacks/dev/platform
        run: |
            terraform init -upgrade
            ###terraform state rm module.keyvault.azurerm_key_vault.this

      - name: Terraform Plan Modules
        working-directory: ./azure-enterprise-terraform/terraform/stacks/dev/platform
        run: terraform plan -lock-timeout=5m -var-file=dev.tfvars

    #   - name: Terraform Apply Modules
    #     working-directory: ./azure-enterprise-terraform/terraform/stacks/dev/platform
    #     run: terraform apply -lock-timeout=5m -auto-approve -var-file=dev.tfvars

    #   - name: Terraform Destroy Modules
    #     working-directory: ./azure-enterprise-terraform/terraform/stacks/dev/platform
    #     run: terraform destroy -lock-timeout=5m -auto-approve -var-file=dev.tfvars

      - name: Terraform Init RGs
        working-directory: ./azure-enterprise-terraform/terraform/global/resource_grouping
        run: |
            terraform init -upgrade

      - name: Terraform Plan RGs
        working-directory: ./azure-enterprise-terraform/terraform/global/resource_grouping
        run: terraform plan -lock-timeout=5m -var-file=dev.auto.tfvars

      - name: Terraform Apply RGs
        working-directory: ./azure-enterprise-terraform/terraform/global/resource_grouping
        run: terraform apply -lock-timeout=5m -auto-approve -var-file=dev.autotfvars

      - name: Terraform Init workkloads
        working-directory: ./azure-enterprise-terraform/terraform/stacks/dev/workloads
        run: |
            terraform init -upgrade

      - name: Terraform Plan workloads
        working-directory: ./azure-enterprise-terraform/terraform/stacks/dev/workloads
        run: terraform plan -lock-timeout=5m -var-file=dev.tfvars

    #   - name: Terraform Apply Modules
    #     working-directory: ./azure-enterprise-terraform/terraform/stacks/dev/platform
    #     run: terraform apply -lock-timeout=5m -auto-approve -var-file=dev.tfvars

    #   - name: Terraform Destroy workloads
    #     working-directory: ./azure-enterprise-terraform/terraform/stacks/dev/workloads
    #     run: terraform destroy -lock-timeout=5m -auto-approve -var-file=dev.tfvars